version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
      - PGTZ=Asia/Almaty
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
      - PGTZ=Asia/Almaty
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latte -d frappuccino"]
      interval: 10s
      timeout: 5s
      retries: 5
